# docker-compose scale spawner=8
version: "3.4"


services:
    nginx:
        image: nginx:1.21-alpine
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - mongo
        command: ["nginx", "-g", "daemon off;"]


